# Generated by Django 4.1 on 2022-11-10 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_dishtype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['name'], 'verbose_name': 'dish', 'verbose_name_plural': 'dishes'},
        ),
    ]
