# Generated by Django 4.1 on 2022-11-10 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_dish_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishtype',
            options={'ordering': ['name'], 'verbose_name': 'dish_type', 'verbose_name_plural': 'dishes_types'},
        ),
    ]
